### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by DHekstra**

### CODE REVIEW

**Comment by DHekstra** [comment]
In this PR:
- added careless_report.py. Should be able to run `$ python careless_report.py -p prefix` in any Careless output dir and get multiplicity, completeness, F/sigF; if xval files: Rsplit, CC1/2, CCanom; if predictions files: CCpred.
- added rsplit.py
- modified ccanom.py, ccpred.py, cchalf.py to be able to directly call the functions that calculate these statistics from notebooks and other scripts, and to be able to provide rs.DataSet objects as input, in addition to being able to provide mtz filenames. I removed 'overall' flags and now have these functions return a dataframe with output per bin and overall statistics.
- added summary_stats.py, which contains some helper functions, including a function, parse_xval_stats, that formats the output from analyze_cchalf_mtz(), analyze_ccanom_mtz(), analyze_rsplit_mtz()
- a notebook, dataset_statistics.ipynb, that shows how to use these functions to analyze Careless output in a notebook.
- a unit_tests.sh script that contains all the tests I ran to check that everything works as intended. The example Careless processing runs used for testing live in `/n/holyscratch01/hekstra_lab/Lab/rsbooster_tests`

**Comment by JBGreisman** [comment]
before I do a full review here, there are few general structure issues:

- Please remove the `src/` directories. There seem to be 3 extra `rs-booster` which shouldn't be a part of this update
- The `unit_tests.sh` seems useful for your testing/development, but for this package we use `pytest` for writing unit tests. Please check out the [tests directory](https://github.com/rs-station/rs-booster/tree/main/tests) for some examples, or the equivalent tests in `reciprocalspaceship` for more extensive examples. There is also some documentation for how to run these sorts of tests [here](https://hekstra-lab.github.io/reciprocalspaceship/developers/testing.html). These tests are automatically run in this PR, and they are currently failing which means this PR currently breaks the tests (or more likely, has an error that prevents it from being imported currently).
- I also think we should think of this library as more of a set of add-on tools for `reciprocalspaceship`. I don't think it's the right place for stashing example notebooks -- I think we should find another location for that. 

More broadly, if these `stats/` tools are becoming very specific/central to `careless` processing, I think we should discuss whether they belong in the `careless` repo itself. Otherwise, I think things may become a bit splintered. @kmdalton -- let me know your thoughts on that.

**Comment by DHekstra** [comment]
- I removed the `src` directories. All checks now pass. I think they failed previously because of a time-out.
- I think the notebook belongs in careless-examples and will remove it from the PR. I included it because it won't run yet without the other content of this PR.

**Comment by JBGreisman** [comment]
Based on our offline discussion, can I close this PR?

**Comment by DHekstra** [comment]
yes, I went ahead and closed it.

**Pull request closed without merging**
