### PR TITLE
Preliminary docs

### PR DESCRIPTION
**Pull request by dennisbrookner**
Working version of documentation, but lacking the automation / workflow situation that would ideally exist!

### CODE REVIEW

**Comment by dennisbrookner** [comment]
By the way, this Latex-y stuff in the `rs.extrapolate` docstring isn't getting rendered in the HTML. I assume there's a way to convince sphinx to render it here; I'm not sure how you would do it without changing how the command-line version looks?
https://github.com/rs-station/rs-booster/blob/a9b93dd2aae86c4400d9862440ae1260f0158449/rsbooster/esf/extrapolate.py#L10

It ends up looking like this, which is a little silly (though also not completely unreadable):
Screenshot 2023-01-04 at 9 30 36 PM

**Comment by dennisbrookner** [comment]
I just remembered that this exists! I think only remaining task is to give this repo a version of something like this:
https://github.com/rs-station/reciprocalspaceship/blob/main/.github/workflows/documentation.yml

Because of how CLI things are exported, I think the right approach here is for anyone adding a new function to just also add it manually to the appropriate place in the docs. Perhaps it could be possible to go through the set of entry points listed in `setup.py` and make sure they're all mentioned in the docs? But that's probably overkill.

**Comment by dennisbrookner** [comment]
The workflow *would* update the docs for existing utilities, if there were changes to the docstrings or arguments or whatnot.

**Comment by JBGreisman** [comment]
I think that's a fine requirement for now -- better to have something. 

We can copy over and modify that `documentation.yml` workflow. We'll also need to set up a `gh-pages` branch with the documentation build that we use to support the hosting -- that's ultimately how it works on reciprocalspaceship

**Comment by dennisbrookner** [comment]
I think I've done this all properly; I'm going to merge this in so that I can test the workflow. The only change to the actual code base was a restructuring of how the `parse_args()` function calls work, and I tested locally that those still work.

**Pull request merged**
